DoAnWebsiteThuCungBento-main/shopban/Controllers/SanphamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using shopban.Models;

namespace shopban.Controllers
{
    public class SanphamController : Controller
    {
        ShopDataDataContext data = new ShopDataDataContext();
        // GET: Sanpham
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult TenNhaCungCap(int id)
        {
            var sp = from s in data.SANPHAMs where s.MaNCC == id select s;
            return View(sp);
        }
        public ActionResult SPLoai(int id)
        {
            var sp = from s in data.SANPHAMs where s.MaL == id select s;
            return View(sp);
        }
        public ActionResult chitietsanpham(int id)
        {
            var sp = from s in data.SANPHAMs where s.MaSP == id select s;
            return View(sp);
        }
        public ActionResult SPDanhMuc(int id)
        {
            var sp = from s in data.SANPHAMs
                     join l in data.LOAIs
                     on s.MaL equals l.MaL
                     where l.MaDM == id
                     select new SanPham_Loai {
                         MaSp = s.MaSP,
                         MaLoai = l.MaL,
                         TenSp = s.TenSP,
                         Anhbia = s.Anhbia,
                         Mota = s.Mota,
                         Gia = s.Giaban,
                     };
            return View(sp);
        }
       
    }
}

DoAnWebsiteThuCungBento-main/shopban/Views/Sanpham/SPDanhMuc.cshtml
@model IEnumerable<shopban.Models.SanPham_Loai>
@{
    ViewBag.Title = "SPDanhMuc";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="shop-category-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12 ">
                <div class="shop-bottom-area mt-35">
                    <div class="tab-content jump">
                        <div id="shop-1" class="tab-pane active">
                            <div class="row">
                                @foreach (var i in Model)
                                {                                
                                    <div class=" col-md-4 col-sm-6 " style="margin-top: 10px; margin-bottom: 20px;">
                                        <div class="slider-single-item">
                                            <!-- Single Item -->
                                            <article class="list-product text-left">
                                                <div class="product-inner">
                                                    <div class="img-block">
                                                        <a href="@Url.Action("chitietsanpham","Sanpham",new {id = i.MaSp })" class="thumbnail">
                                                            <img class="first-img" src="@i.Anhbia" alt="" />
                                                            <img class="second-img" src="@i.Anhbia" alt="" />
                                                        </a>
                                                        <div class="add-to-link">
                                                            <ul>
                                                                <li>
                                                                    <a href="wishlist.html" title="Add to Wishlist"><i class="las la-heart"></i></a>
                                                                </li>
                                                                <li>
                                                                    <a href="compare.html" title="Add to compare"><i class="las la-sync"></i></a>
                                                                </li>
                                                                <li>
                                                                    <a class="quick_view" href="@Url.Action("chitietsanpham","Sanpham",new {id = i.MaSp })">
                                                                        <i class="las la-search"></i>
                                                                    </a>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                        <ul class="product-flag">
                                                            <li class="new">New</li>
                                                            @* <li class="new discount">-5%</li>*@
                                                        </ul>
                                                    </div>
                                                    <div class="product-decs">
                                                        <h2><a href="@Url.Action("chitietsanpham","Sanpham",new {id = i.MaSp })" class="product-link">@i.TenSp</a></h2>
                                                        <div class="pricing-meta">
                                                            <ul>
                                                                
                                                                <li class="current-price">@String.Format("{0:0,0 vn₫}", i.Gia)</li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                    <div class="cart-btn">
                                                        <a href="@Url.Action("ThemGiohang", "GioHang", new { @iMaSp = i.MaSp , @strURL=Request.Url.ToString() })" class="add-to-curt" title="Thêm vào giỏ hàng"><i class="las la-baby-carriage"></i></a>
                                                    </div>
                                                </div>
                                            </article>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

DoAnWebsiteThuCungBento-main/shopban/Views/Sanpham/SPLoai.cshtml
@model IEnumerable<shopban.Models.SANPHAM>
@{
    ViewBag.Title = "SPLoai";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="shop-category-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12 ">
                <div class="shop-bottom-area mt-35">
                    <div class="tab-content jump">
                        <div id="shop-1" class="tab-pane active">
                            <div class="row">
                                @foreach (var i in Model)
                                {
                                    <div class=" col-md-4 col-sm-6 " style="margin-top: 10px; margin-bottom: 20px;">
                                        <div class="slider-single-item">
                                            <!-- Single Item -->
                                            <article class="list-product text-left">
                                                <div class="product-inner">
                                                    <div class="img-block">
                                                        <a href="single-product.html" class="thumbnail">
                                                            <img class="first-img" src="@i.Anhbia" alt="" />
                                                            <img class="second-img" src="@i.Anhbia" alt="" />
                                                        </a>
                                                        <div class="add-to-link">
                                                            <ul>
                                                                <li>
                                                                    <a class="quick_view" href="@Url.Action("chitietsanpham","Sanpham",new {id = i.MaSP })">
                                                                        <i class="las la-search" style="color:deeppink"></i><p style="color: black">Nhấn để xem chi tiết</p>
                                                                    </a>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                        <ul class="product-flag">
                                                            <li class="new">New</li>
                                                           @* <li class="new discount">-5%</li>*@
                                                        </ul>
                                                    </div>
                                                    <div class="product-decs">
                                                        <h2><a href="@Url.Action("chitietsanpham","Sanpham",new {id = i.MaSP })" class="product-link">@i.TenSP</a></h2>
                                                        <div class="pricing-meta">
                                                            <ul>
                                                                <li class="current-price">@String.Format("{0:0,0 vn₫}", i.Giaban)</li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                    <div class="cart-btn">
                                                        <a href="@Url.Action("ThemGiohang", "GioHang", new { @iMaSp = i.MaSP , @strURL=Request.Url.ToString() })" class="add-to-curt" title="Thêm vào giỏ hàng"><i class="las la-baby-carriage"></i></a>
                                                    </div>
                                                </div>
                                            </article>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

DoAnWebsiteThuCungBento-main/shopban/Views/Sanpham/TenNhaCungCap.cshtml
@model IEnumerable<shopban.Models.SANPHAM>
@{
    ViewBag.Title = "TenNhaCungCap";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="shop-category-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12 ">
                <div class="shop-bottom-area mt-35">
                    <div class="tab-content jump">
                        <div id="shop-1" class="tab-pane active">
                            <div class="row">
                                @foreach (var i in Model)
                                {
                                    <div class=" col-md-4 col-sm-6 " style="margin-top:10px; margin-bottom:20px;">
                                        <div class="slider-single-item">
                                            <!-- Single Item -->
                                            <article class="list-product text-left">
                                                <div class="product-inner">
                                                    <div class="img-block">
                                                        <a href="single-product.html" class="thumbnail">
                                                            <img class="first-img" src="@i.Anhbia" alt="" />
                                                            <img class="second-img" src="@i.Anhbia" alt="" />
                                                        </a>
                                                        <div class="add-to-link">
                                                            <ul>
                                                                <li>
                                                                    <a class="quick_view" href="@Url.Action("chitietsanpham","Sanpham",new {id = i.MaSP })">
                                                                        <i class="las la-search" style="color:deeppink"></i><p style="color: black">Nhấn để xem chi tiết</p>
                                                                    </a>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                        <ul class="product-flag">
                                                            <li class="new">New</li>
                                                            @* <li class="new discount">-5%</li>*@
                                                        </ul>
                                                    </div>
                                                    <div class="product-decs">
                                                        <h2><a href="@Url.Action("chitietsanpham","Sanpham",new {id = i.MaSP })" class="product-link">@i.TenSP</a></h2>
                                                        <div class="pricing-meta">
                                                            <ul>
                                                                <li class="current-price">@String.Format("{0:0,0}", i.Giaban)</li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                    <div class="cart-btn">
                                                        <a href="@Url.Action("ThemGiohang", "GioHang", new { @iMaSp = i.MaSP , @strURL=Request.Url.ToString() })" class="add-to-curt" title="Add to cart"><i class="las la-baby-carriage"></i></a>
                                                    </div>
                                                </div>
                                            </article>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

DoAnWebsiteThuCungBento-main/shopban/Views/Sanpham/chitietsanpham.cshtml
@model IEnumerable<shopban.Models.SANPHAM>
@{
    ViewBag.Title = "chitietsanpham";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@foreach (var i in Model)
{
    <div class="product-details-area">
        <div class="container">
            <div class="row">
                <div class="col-xl-6 col-lg-6 col-md-6">
                    <div class="product-details-img product-details-tab position-relative">
                        <!--ảnh to ở trên -->
                        <div class="zoompro-wrap zoompro-2">
                            <div class="zoompro-border zoompro-span">
                                <img class="zoompro w-100" src="@i.Anhbia" data-zoom-image="@i.Anhbia" alt="" />
                            </div>

                        </div>
                        <!--ảnh nhỏ ở dưới -->
                        <div id="gallery" class="product-dec-slider-2">
                            <div class="single-slide-item">
                                <img class="img-responsive" data-image="@i.Anhbia" data-zoom-image="@i.Anhbia" src="@i.Anhbia" alt="" />
                            </div>

                        </div>
                        <ul class="product-flag">
                            <li class="new">Mới</li>
                        </ul>
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6">
                    <div class="product-details-content">
                        <h2>@i.TenSP</h2>
                        <div class="pricing-meta">
                            <ul>

                                <li class="cuttent-price">@String.Format("{0:0,0 vn₫}", i.Giaban)</li>
                            </ul>
                        </div>
                        <div class="pro-details-list">
                            <ul>
                                <li>@i.Mota</li>

                            </ul>
                        </div>
                        <div class="pro-details-quality mt-0px">
                            <div class="cart-plus-minus">
                                <input class="cart-plus-minus-box" type="text" name="qtybutton" value="1" />
                            </div>
                            <div class="pro-details-cart btn-hover">
                                <a href="@Url.Action("ThemGiohang", "GioHang", new { @iMaSp = i.MaSP , @strURL=Request.Url.ToString() })">Thêm vào giỏ hàng</a>
                            </div>
                        </div>
                        <div class="pro-details-wish-com">
                            <div class="pro-details-wishlist">
                                <a href="#"><i class="las la-heart"></i></a>
                            </div>
                            <div class="pro-details-compare">
                                <a href="#"><i class="las la-sync"></i></a>
                            </div>
                        </div>
                        <div class="pro-details-social-info">
                            <span>Share</span>
                            <div class="social-info">
                                <ul>
                                    <li>
                                        <a title="Facebook" href="#"><i class="ion-social-facebook"></i></a>
                                    </li>
                                    <li>
                                        <a title="Twitter" href="#"><i class="ion-social-twitter"></i></a>
                                    </li>
                                    <li>
                                        <a title="Google+" href="#"><i class="ion-social-google"></i></a>
                                    </li>
                                    <li>
                                        <a title="Instagram" href="#"><i class="ion-social-instagram"></i></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="pro-details-policy">
                            <ul>
                                <li><img src="~/assets/images/icons/policy.png" alt="" /><span>Chính sách vận chuyển (Giao hàng miễn phí)</span></li>
                                <li><img src="~/assets/images/icons/policy-2.png" alt="" /><span>Chính sách giao/nhận (Thanh toán khi nhận hàng. (Không được đồng kiểm))</span></li>
                                <li><img src="~/assets/images/icons/policy-3.png" alt="" /><span>Chính sách hoàn trả (15 ngày trả hàng)</span></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Shop details Area End -->
    <!-- product details description area start -->
    <div class="description-review-area mb-50px bg-light-gray-3 ptb-50px">
        <div class="container">
            <div class="description-review-wrapper">
                <div class="description-review-topbar nav">
                    <a data-toggle="tab" href="#des-details1">Mô tả</a>

                    <a data-toggle="tab" href="#des-details3">Nhận xét/Đánh giá (2)</a>
                </div>
                <div class="tab-content description-review-bottom">

                    <div id="des-details1" class="tab-pane">
                        <div class="product-description-wrapper">
                            <p>@i.Mota</p>
                        </div>
                    </div>
                    <div id="des-details3" class="tab-pane">
                        <div class="row">
                            <div class="col-lg-7">
                                <div class="review-wrapper">
                                    <div class="single-review">
                                        <div class="review-img">
                                            <img src="~/assets/images/review-image/1.png" alt="" />
                                        </div>
                                        <div class="review-content">
                                            <div class="review-top-wrap">
                                                <div class="review-left">
                                                    <div class="review-name">
                                                        <h4>Lưu Gia Thanh</h4>
                                                    </div>
                                                    <div class="rating-product">
                                                        <i class="ion-android-star"></i>
                                                        <i class="ion-android-star"></i>
                                                        <i class="ion-android-star"></i>
                                                        <i class="ion-android-star"></i>
                                                        <i class="ion-android-star"></i>
                                                    </div>
                                                </div>
                                                <div class="review-left">
                                                    <a href="#">Reply</a>
                                                </div>
                                            </div>
                                            <div class="review-bottom">
                                                <p>
                                                    Sản phẩm rất tuyệt vời!
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="single-review child-review">
                                        <div class="review-img">
                                            <img src="~/assets/images/review-image/2.png" alt="" />
                                        </div>
                                        <div class="review-content">
                                            <div class="review-top-wrap">
                                                <div class="review-left">
                                                    <div class="review-name">
                                                        <h4>Nguyễn Tấn Tài</h4>
                                                    </div>
                                                    <div class="rating-product">
                                                        <i class="ion-android-star"></i>
                                                        <i class="ion-android-star"></i>
                                                        <i class="ion-android-star"></i>
                                                        <i class="ion-android-star"></i>
                                                        <i class="ion-android-star"></i>
                                                    </div>
                                                </div>
                                                <div class="review-left">
                                                    <a href="#">Reply</a>
                                                </div>
                                            </div>
                                            <div class="review-bottom">
                                                <p>Ok, bạn nhá!</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-5">
                                <div class="ratting-form-wrapper pl-50">
                                    <h3>Review cửa hàng</h3>
                                    <div class="ratting-form">
                                        <form action="#">
                                            <div class="star-box">
                                                <span>Đánh giá:</span>
                                                <div class="rating-product">
                                                    <i class="ion-android-star"></i>
                                                    <i class="ion-android-star"></i>
                                                    <i class="ion-android-star"></i>
                                                    <i class="ion-android-star"></i>
                                                    <i class="ion-android-star"></i>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="rating-form-style mb-10">
                                                        <input placeholder="Họ tên" type="text" />
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="rating-form-style mb-10">
                                                        <input placeholder="Email" type="email" />
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="rating-form-style form-submit">
                                                        <textarea name="Review của bạn về cửa hàng" placeholder="Bình luận"></textarea>
                                                        <input type="submit" value="Gửi" />
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<div class="related-item">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title">
                    <h2>CÓ THỂ BẠN SẼ THÍCH</h2>
                </div>
            </div>
        </div>
        <!-- Tab Slider Start -->
        <div class="arrival-slider slider-nav-style-1">
           @Html.Action("SanPhamBanChay", "Home");
        </div>
        <!-- Tab Slider End -->
    </div>
</div>